# Generated by Django 4.0.4 on 2024-04-25 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
        ('user', '0004_auto_20230419_0603'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=500)),
                ('time', models.DateTimeField()),
                ('productLine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productline')),
                ('user', models.ManyToManyField(to='user.users')),
            ],
        ),
    ]
