# Generated by Django 4.0.4 on 2024-04-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarms',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
