# Generated by Django 4.0.4 on 2023-03-25 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLinePart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productline')),
            ],
        ),
        migrations.CreateModel(
            name='SettingsType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('field', models.CharField(max_length=255)),
                ('syntax', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start_at', models.TimeField(blank=True, null=True)),
                ('ends_at', models.TimeField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('inputs', models.CharField(max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
                ('settings_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.settingstype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLinePart2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('product_line_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productlinepart')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryMember',
            fields=[
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.users')),
                ('status', models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=10)),
                ('factory', models.ManyToManyField(blank=True, to='factory.factory')),
                ('product_line_id', models.ManyToManyField(blank=True, to='factory.productline')),
            ],
        ),
    ]
