# Generated by Django 4.0.4 on 2022-05-29 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_users_deleted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('delete', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLinePart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productline')),
            ],
        ),
        migrations.CreateModel(
            name='FactoryMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
            options={
                'unique_together': {('factory', 'member')},
            },
        ),
    ]
