# Generated by Django 4.0.4 on 2022-05-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='ends_at',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
