# Generated by Django 4.0.4 on 2022-05-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_alter_shift_ends_at_alter_shift_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorymember',
            name='status',
            field=models.CharField(choices=[('ENABLED', 'ENABLED'), ('DISABLED', 'DISABLED')], default='ENABLED', max_length=10),
        ),
    ]
