# Generated by Django 4.0.4 on 2023-04-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0002_remove_factorymember_product_line_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factorymember',
            name='product_line',
            field=models.ManyToManyField(blank=True, db_constraint=False, default=[], to='factory.productline'),
        ),
    ]
