# Generated by Django 4.0.4 on 2022-06-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0003_alter_factorymember_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLinePart2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255)),
                ('product_line_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productlinepart')),
            ],
        ),
    ]
