# Generated by Django 4.0.4 on 2022-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('field', models.CharField(max_length=255)),
                ('syntax', models.CharField(max_length=255)),
            ],
        ),
    ]
