# Generated by Django 4.0.4 on 2022-08-13 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0006_settingstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='settings_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factory.settingstype'),
            preserve_default=False,
        ),
    ]
