# Generated by Django 4.0.4 on 2022-08-17 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0007_settings_settings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='settings_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='factory.settingstype'),
        ),
    ]
