# Generated by Django 4.0.4 on 2023-04-04 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsrole',
            name='operation_type_id',
        ),
        migrations.RemoveField(
            model_name='permissionsrole',
            name='permissions_id',
        ),
        migrations.RemoveField(
            model_name='permissionsrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.DeleteModel(
            name='OperationsTypes',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='PermissionsRole',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
