# Generated by Django 4.0.4 on 2022-05-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
