# Generated by Django 3.2.13 on 2023-04-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_users_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionsrole',
            name='operation_type_id',
        ),
        migrations.RemoveField(
            model_name='permissionsrole',
            name='permissions_id',
        ),
        migrations.RemoveField(
            model_name='permissionsrole',
            name='role_id',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='city',
        ),
        migrations.RemoveField(
            model_name='users',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.RemoveField(
            model_name='users',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='OperationsTypes',
        ),
        migrations.DeleteModel(
            name='Permissions',
        ),
        migrations.DeleteModel(
            name='PermissionsRole',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
