# Generated by Django 4.0.4 on 2023-01-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_settings_settings_type'),
        ('device', '0002_alter_device_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineDevice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50)),
                ('port', models.CharField(max_length=10)),
                ('position', models.IntegerField()),
                ('data', models.CharField(max_length=1050)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('device_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.devicetype')),
                ('product_line_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productlinepart')),
            ],
        ),
    ]
