# Generated by Django 4.0.4 on 2023-01-08 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_linedevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedevice',
            name='product_line_part',
            field=models.CharField(max_length=10),
        ),
    ]
