# Generated by Django 4.0.4 on 2023-01-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_alter_linedevice_product_line_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedevice',
            name='data',
            field=models.CharField(default='', max_length=1050),
        ),
        migrations.AlterField(
            model_name='linedevice',
            name='port',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='linedevice',
            name='position',
            field=models.IntegerField(default=''),
        ),
    ]
