# Generated by Django 4.0.4 on 2023-01-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0008_alter_settings_settings_type'),
        ('device', '0005_alter_linedevice_data_alter_linedevice_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedevice',
            name='product_line_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.productlinepart'),
        ),
    ]
