# Generated by Django 4.0.4 on 2023-01-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0006_alter_linedevice_product_line_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_vital', models.BooleanField(default=False)),
                ('section', models.CharField(choices=[('stacker', 'stacker'), ('packaging machine', 'packaging machine')], max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='linedevice',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='linedevice',
            name='product_line_part',
        ),
    ]
