# Generated by Django 4.0.4 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0007_errorline_remove_linedevice_device_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorline',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
