# Generated by Django 4.0.4 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0008_errorline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorline',
            name='code',
            field=models.IntegerField(),
        ),
    ]
