# Generated by Django 4.0.4 on 2023-02-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_alter_errorline_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineDevice',
        ),
        migrations.RemoveField(
            model_name='errorline',
            name='is_vital',
        ),
        migrations.AlterField(
            model_name='errorline',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
