# Generated by Django 4.0.4 on 2023-02-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_remove_errorline_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorline',
            name='is_vital',
        ),
        migrations.AddField(
            model_name='errorline',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
