# Generated by Django 4.0.4 on 2023-02-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_remove_errorline_is_vital_errorline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorline',
            name='code',
            field=models.IntegerField(),
        ),
    ]
