# Generated by Django 4.0.4 on 2023-02-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0013_alter_errorline_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorline',
            name='section',
            field=models.CharField(max_length=30),
        ),
    ]
